export const allMatches = [

  {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "16:30",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland"],
        team2: ["2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        yellows: [],
        reds: [],
        goals: [],
        clean_sheets: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland", "2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        penalties_missed: [],
        motm: "Maignan",
        events: ["First game of the year", "Great play from Kane, hold up and passing", "Maignan makes several great saves in the game, one on Kane"]
      },
      {
        id: 2,
        month: "january",
        match_number: 2,
        date: "02/01/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ["Bruney", "Walker", "Berbatov", "Griezmann", "Neymar", "Morata"],
        team2: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        yellows: ["Morata", "Berbatov"],
        reds: [],
        goals: [
          { p: "Jobe", a: "", special: "Penalty", side: "team2" },
        ],
        clean_sheets: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        penalties_missed: [],
        motm: "Jobe",
        events: ['Jobe wins the penalty by shooting and Berbatov blocks it with his hand']
      },
      {
        id: 3,
        month: "january",
        match_number: 3,
        date: "05/01/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane"],
        team2: ["Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane", "Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        penalties_missed: [],
        motm: "Olmo",
        events: ['Olmo and Van Persie smash the post', 'Berbatov has played 3/3 games']
      },

      /*
    {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "",
        referee: "",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: [""],
        team2: [""],
        yellows: [""],
        reds: [],
        goals: [
            { p: "Pele", a: "Kroos", special: "Slinger", side: "team1" },

          ],
        penalties_missed: [],
        motm: "",
      },
  */
]