export const allMatches = [

  {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "16:30",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland"],
        team2: ["2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        yellows: [],
        reds: [],
        goals: [],
        clean_sheets: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland", "2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        penalties_missed: [],
        motm: "Maignan",
        events: ["First game of the year", "Great play from Kane, hold up and passing", "Maignan makes several great saves in the game, one on Kane"]
      },
      {
        id: 2,
        month: "january",
        match_number: 2,
        date: "02/01/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ["Bruney", "Walker", "Berbatov", "Griezmann", "Neymar", "Morata"],
        team2: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        yellows: ["Morata", "Berbatov"],
        reds: [],
        goals: [
          { p: "Jobe", a: "", special: "Penalty", side: "team2" },
        ],
        clean_sheets: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        penalties_missed: [],
        motm: "Jobe",
        events: ['Jobe wins the penalty by shooting and Berbatov blocks it with his hand']
      },
      {
        id: 3,
        month: "january",
        match_number: 3,
        date: "05/01/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane"],
        team2: ["Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane", "Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        penalties_missed: [],
        motm: "Olmo",
        events: ['Olmo and Van Persie smash the post', 'Berbatov has played 3/3 games']
      },
      {
        id: 4,
        month: "january",
        match_number: 4,
        date: "08/01/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['Van Der Sar', 'Russian Def', 'Berbatov', 'Barella', 'Pele', 'Lewandowski'],
        team2: ['Bruney', 'Lampard', 'Saka', 'Jobe', 'Messi (ft)', 'Benzema'],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ['Van Der Sar', 'Russian Def', 'Berbatov', 'Barella', 'Pele', 'Lewandowski', 'Bruney', 'Lampard', 'Saka', 'Jobe', 'Messi (ft)', 'Benzema'],
        penalties_missed: [],
        motm: "Pele",
        events: ['Pele dirty nut megs throughout the game', 'Berbatov has now played 4/4 games']
      },
      {
        id: 5,
        month: "january",
        match_number: 5,
        date: "13/01/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ['Courtois', 'Puyol', 'Van Persie', 'Pedri', 'Neymar', 'Kane'],
        team2: ['Van Der Sar', 'Hummels', 'Berbatov', 'Modric', 'Vinicius', 'Suarez'],
        yellows: ['Suarez'],
        reds: [],
        goals: [
          { p: "Vinicius", a: "Modric", special: "", side: "team2" },
        ],
        clean_sheets: ['Van Der Sar', 'Hummels', 'Berbatov', 'Modric', 'Vinicius', 'Suarez'],
        penalties_missed: [],
        motm: "Modric",
        events: ['Berbatov has now played 5/5 games']
      },
      {
        id: 6,
        month: "january",
        match_number: 6,
        date: "15/01/2026",
        time: "17:05",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 3,
        team1: ['Russian Keeper', 'Hummels', 'Joaquin', 'Eriksen', 'Gakpo', 'Lewandowski'],
        team2: ['2-Face', 'Puyol', 'Assuncao', 'Pedri', 'Bale', 'Martinez'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Martinez", a: "Pedri", special: "", side: "team2" },
          { p: "Bale", a: "Martinez", special: "", side: "team2" },
          { p: "Pedri", a: "Bale", special: "", side: "team2" },
        ],
        clean_sheets: ['2-Face', 'Puyol', 'Assuncao', 'Pedri', 'Bale', 'Martinez'],
        penalties_missed: [],
        motm: "Martinez",
        events: ['Bale cut in on Joaquin and bent it top corner finesse', 'Pedri diving header, got it just in front of Martinez']
      },
      {
        id: 7,
        month: "january",
        match_number: 7,
        date: "27/01/2026",
        time: "17:00",
        referee: "Refil",
        condition: "Clear",
        team1_score: 1,
        team2_score: 1,
        team1: ['Cech', 'Puyol', 'Torres', 'Bellingham', 'Bale', 'Benzema'],
        team2: ['Neuer', 'Russian Def', 'Joaquin', 'Pedri', 'Saka', 'Morata'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Morata", a: "Joaquin", special: "volley", side: "team2" },
          { p: "Bellingham", a: "Benzema", special: "", side: "team1" },
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "",
        events: ['Morata with a powerful volley from Joaquin cross', 'Russian Def made some defensive errors but also hit the post', 'Bellingham with a late equalizer after a Benzema shot was deflected onto him in the bottom right corner' ]
      },
      {
        id: 8,
        month: "january",
        match_number: 8,
        date: "28/01/2026",
        time: "17:00",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ['2-Face', 'Lampard', 'Gallas', 'Valverde', 'Bowen', 'Schranz'],
        team2: ['Russian Keeper', 'Russian Def', 'Joaquin', 'Jobe', 'Gakpo', 'Alvarez'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Jobe", a: "Alvarez", special: "", side: "team2" },
        ],
        clean_sheets: ['Russian Keeper', 'Russian Def', 'Joaquin', 'Jobe', 'Gakpo', 'Alvarez'],
        penalties_missed: [],
        motm: "Jobe",
        events: ['Alvarez little flick to Jobe, who hit it top left bar and in', 'Gakpo was racist to Gallas all game', 'Gallas had good technical dribbling throughout the game', 'Russian Def cut of the meat and let it run out of play, worked perfectly', 'Jobe scores his second goal of the season' ]
      },
      {
        id: 9,
        month: "february",
        match_number: 9,
        date: "04/02/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['2-Face', 'Hummels', 'Berbatov', 'Valverde', 'Saka', 'Ronaldo'],
        team2: ['Stackers', 'Walker', 'Van Persie', 'Modric', 'Bale', 'Benzema'],
        yellows: ['Van Persie'],
        reds: [],
        goals: [
        ],
        clean_sheets: ['2-Face', 'Hummels', 'Berbatov', 'Valverde', 'Saka', 'Ronaldo', 'Stackers', 'Walker', 'Van Persie', 'Modric', 'Bale', 'Benzema'],
        penalties_missed: [],
        motm: "",
        events: ['Exciting battle between Van Persie and Ronaldo']
      },
      {
        id: 10,
        month: "february",
        match_number: 10,
        date: "05/02/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 1,
        team2_score: 0,
        team1: ['Van Der Sar', 'Hummels', 'Van Persie', 'Bellingham', 'Saka', 'Kane'],
        team2: ['Bruney', 'Vidic', 'Ramos', 'Olmo', 'Mbappe', 'Ronaldo'],
        yellows: ['Saka'],
        reds: [],
        goals: [
          { p: "Bellingham", a: "Saka", special: "", side: "team1" },
        ],
        clean_sheets: ['Van Der Sar', 'Hummels', 'Van Persie', 'Bellingham', 'Saka', 'Kane'],
        penalties_missed: [],
        motm: "Bellingham",
        events: ['Saka cross and Bellingham ran in front of Vidic and perfect contact, roof of the net']
      },
      {
        id: 11,
        month: "february",
        match_number: 11,
        date: "09/02/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ['Lloris', 'Hummels', 'Silva', 'Bellingham', 'Mbappe', 'Ronaldo'],
        team2: ['Cech', 'Vicente', 'Berbatov', 'Jobe', 'Dembele', 'Schranz'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Jobe", a: "Schranz", special: "", side: "team2" },
        ],
        clean_sheets: ['Cech', 'Vicente', 'Berbatov', 'Jobe', 'Dembele', 'Schranz'],
        penalties_missed: [],
        motm: "Cech",
        events: ['Cech made loads of saves', 'Jobe with a great finish, side netting powerful, lay off from Schranz', 'Great target man game from Schranz, bullied Hummels and the others at times']
      },
      {
        id: 12,
        month: "february",
        match_number: 12,
        date: "22/02/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 2,
        team2_score: 1,
        team1: ['Neuer', 'Hummels', 'Tevez', 'Musiala', 'Messi', 'Haaland'],
        team2: ['Mendy', 'Vidic', 'Raul', 'Jobe', 'Mbappe', 'Lewandowski'],
        yellows: ['Musiala'],
        reds: [],
        goals: [
          { p: "Tevez", a: "Haaland", special: "slinger", side: "team1" },
          { p: "Mbappe", a: "", special: "Penalty", side: "team2" },
          { p: "Musiala", a: "Haaland", special: "", side: "team1" },
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "Haaland",
        events: ['Tevez quick shot slinger', 'Musiala great touches and passes, finish was across the goal on the floor at the end', 'Mbappe done Hummels to win the penalty']
      },
      {
        id: 13,
        month: "february",
        match_number: 13,
        date: "23/02/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 1,
        team2_score: 1,
        team1: ['Stackers', 'Caveman', 'Silva', 'Rodri', 'Pele', 'Lewandowski'],
        team2: ['Van Der Sar', 'Walker', 'Tevez', 'Griezmann', 'Vinicius', 'Schranz'],
        yellows: ['Vinicius'],
        reds: [],
        goals: [
          { p: "Pele", a: "Lewandowski", special: "", side: "team1" },
          { p: "Vinicius", a: "Griezmann", special: "slinger", side: "team2" },
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "Vinicius",
        events: ['Pele dragged it onto weaker foot and placement, nearly a slinger', 'Vinicius cuts in and bang it and goes into slinger']
      },
      {
        id: 14,
        month: "february",
        match_number: 14,
        date: "24/02/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 2,
        team2_score: 1,
        team1: ['Van Der Sar', 'Vidic', 'Tevez', 'Rodri', 'Yamal', 'Haaland'],
        team2: ['Stackers', 'Black Hair', 'Van Persie', 'Pedri', 'Saka', 'Morata'],
        yellows: ['Van Persie'],
        reds: [],
        goals: [
          { p: "Yamal", a: "Tevez", special: "", side: "team1" },
          { p: "Haaland", a: "Yamal", special: "", side: "team1" },
          { p: "Pedri", a: "Van Persie", special: "", side: "team2" },
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "Yamal",
        events: ['Yamal cut out on Persie and whipped it in top corner and it went around the goal', 'Probably goal of the season so far', 'Yamal ripped Van Persie all game, skills and dribble', 'Probbaly best individual performance this year so far', 'Dropped a 10.0']
      },
      {
        id: 15,
        month: "march",
        match_number: 15,
        date: "02/03/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['Courtois', 'Caveman', 'Raul', 'Olmo', 'Messi', 'Ronaldo'],
        team2: ['Van Der Sar', 'Black Hair', 'Silva', 'Modric', 'Neymar', 'Suarez'],
        yellows: ['Messi'],
        reds: [],
        goals: [
        ],
        clean_sheets: ['Courtois', 'Caveman', 'Raul', 'Olmo', 'Messi', 'Ronaldo', 'Van Der Sar', 'Black Hair', 'Silva', 'Modric', 'Neymar', 'Suarez'],
        penalties_missed: [],
        motm: "",
        events: ['Messi dirty trip on Black Hair', 'Caveman and Ronaldo both hit the post']
      },
      {
        id: 16,
        month: "march",
        match_number: 16,
        date: "03/03/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['Van Der Sar', 'Black Hair', 'Tevez', 'Valverde', 'Messi', 'Schranz'],
        team2: ['Boxer', 'Caveman', 'Raul', 'Griezmann', 'Mbappe', 'Haaland'],
        yellows: ['Messi'],
        reds: [],
        goals: [
        ],
        clean_sheets: ['Van Der Sar', 'Black Hair', 'Tevez', 'Valverde', 'Messi', 'Schranz', 'Boxer', 'Caveman', 'Raul', 'Griezmann', 'Mbappe', 'Haaland'],
        penalties_missed: [],
        motm: "",
        events: []
      },
      {
        id: 17,
        month: "march",
        match_number: 17,
        date: "17/03/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 2,
        team2_score: 0,
        team1: ['Boxer', 'Caveman', 'Tevez', 'Pedri', 'Pele', 'Kane'],
        team2: ['Van Der Sar', 'Black Hair', 'Silva', 'Modric', 'Mbappe', 'Ronaldo'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Kane", a: "Pele", special: "", side: "team1" },
          { p: "Kane", a: "Pedri", special: "slinger", side: "team1" }
        ],
        clean_sheets: ['Boxer', 'Caveman', 'Tevez', 'Pedri', 'Pele', 'Kane'],
        penalties_missed: [],
        motm: "Kane",
        events: ['Kane first goal was a diving header right in the corner' , 'Kane second goal was an interception from Pedri on Silva - brilliant tackle, trapped under his head, and then layed it off to Kane who smashed it across goal, hit the post and ended up in the other corners slinger']
      },
      {
        id: 18,
        month: "march",
        match_number: 18,
        date: "18/03/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 2,
        team1: ['Van Der Sar', 'Caveman', 'Silva', 'Barella', 'Mbappe', 'Ronaldo'],
        team2: ['Bruney', 'Black Hair', 'Raul', 'Jobe', 'Bowen', 'Lewandowski'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Jobe", a: "Bowen", special: "", side: "team2" },
          { p: "Raul", a: "Black Hair", special: "", side: "team2" }
        ],
        clean_sheets: ['Bruney', 'Black Hair', 'Raul', 'Jobe', 'Bowen', 'Lewandowski'],
        penalties_missed: [],
        motm: "Black Hair",
        events: ['Jobe great skill on Barella and finesse top corner post and in']
      },
      {
        id: 19,
        month: "march",
        match_number: 19,
        date: "19/03/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 1,
        team2_score: 1,
        team1: ['Courtois', 'Black Hair', 'Torres', 'Modric', 'Pele', 'Kane'],
        team2: ['Cech', 'Puyol', 'Silva', 'Bellingham', 'Messi', 'Ronaldo'],
        yellows: ['Silva', 'Kane'],
        reds: ['Silva'],
        goals: [
          { p: "Ronaldo", a: "", special: "Penalty", side: "team2" },
          { p: "Pele", a: "Modric", special: "", side: "team1" }
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "Ronaldo",
        events: ['Ronaldo great turn on Kane and won the penalty']
      },
      {
        id: 20,
        month: "march",
        match_number: 20,
        date: "20/03/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 1,
        team2_score: 3,
        team1: ['Bruney', 'Trippier', 'Tevez', 'Jobe', 'Messi', 'Suarez'],
        team2: ['Lloris', 'Vidic', 'Raul', 'Bellingham', 'Gakpo', 'Morata'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Morata", a: "Raul", special: "", side: "team2" },
          { p: "Raul", a: "Bellingham", special: "Slinger", side: "team2" },
          { p: "Suarez", a: "Tevez", special: "", side: "team1" },
          { p: "Gakpo", a: "Bellingham", special: "", side: "team2" },
        ],
        clean_sheets: [],
        penalties_missed: [],
        motm: "",
        events: ['Great football between the team for the first goal', 'Raul slinger into the far corner', 'Suarez bar and in longshot', 'Gakpo break at the end and hits it near post']
      },
      {
        id: 21,
        month: "march",
        match_number: 21,
        date: "21/03/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['Van Der Sar', 'Caveman', 'Tevez', 'Pedri', 'Mbappe', 'Muller'],
        team2: ['Lloris', 'Black Hair', 'Van Persie', 'Olmo', 'Bale', 'Suarez'],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ['Van Der Sar', 'Caveman', 'Tevez', 'Pedri', 'Mbappe', 'Muller', 'Lloris', 'Black Hair', 'Van Persie', 'Olmo', 'Bale', 'Suarez'],
        penalties_missed: [],
        motm: "",
        events: ['']
      },



      /*
    {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "",
        referee: "",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: [""],
        team2: [""],
        yellows: [""],
        reds: [],
        goals: [
            { p: "Pele", a: "Kroos", special: "Slinger", side: "team1" },

          ],
        penalties_missed: [],
        motm: "",
      },
  */
]