export const allMatches = [

  {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "16:30",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland"],
        team2: ["2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        yellows: [],
        reds: [],
        goals: [],
        clean_sheets: ["Maignan", "Van Dijk", "Gakpo", "De Bruyne", "Ramos", "Haaland", "2-Face", "Vidic", "Vinicius", "Barella", "Berbatov", "Kane"],
        penalties_missed: [],
        motm: "Maignan",
        events: ["First game of the year", "Great play from Kane, hold up and passing", "Maignan makes several great saves in the game, one on Kane"]
      },
      {
        id: 2,
        month: "january",
        match_number: 2,
        date: "02/01/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ["Bruney", "Walker", "Berbatov", "Griezmann", "Neymar", "Morata"],
        team2: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        yellows: ["Morata", "Berbatov"],
        reds: [],
        goals: [
          { p: "Jobe", a: "", special: "Penalty", side: "team2" },
        ],
        clean_sheets: ["Mendy", "Lampard", "Ramos", "Jobe", "Saka", "Martinez"],
        penalties_missed: [],
        motm: "Jobe",
        events: ['Jobe wins the penalty by shooting and Berbatov blocks it with his hand']
      },
      {
        id: 3,
        month: "january",
        match_number: 3,
        date: "05/01/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane"],
        team2: ["Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ["Courtois", "Sergio", "Yamal", "Olmo", "Berbatov", "Kane", "Bruney", "Russian Def", "Mbappe", "Bellingham", "Van Persie", "Benzema"],
        penalties_missed: [],
        motm: "Olmo",
        events: ['Olmo and Van Persie smash the post', 'Berbatov has played 3/3 games']
      },
      {
        id: 4,
        month: "january",
        match_number: 4,
        date: "08/01/2026",
        time: "17:15",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: ['Van Der Sar', 'Russian Def', 'Berbatov', 'Barella', 'Pele', 'Lewandowski'],
        team2: ['Bruney', 'Lampard', 'Saka', 'Jobe', 'Messi (ft)', 'Benzema'],
        yellows: [],
        reds: [],
        goals: [
        ],
        clean_sheets: ['Van Der Sar', 'Russian Def', 'Berbatov', 'Barella', 'Pele', 'Lewandowski', 'Bruney', 'Lampard', 'Saka', 'Jobe', 'Messi (ft)', 'Benzema'],
        penalties_missed: [],
        motm: "Pele",
        events: ['Pele dirty nut megs throughout the game', 'Berbatov has now played 4/4 games']
      },
      {
        id: 5,
        month: "january",
        match_number: 5,
        date: "13/01/2026",
        time: "17:15",
        referee: "Refil",
        condition: "Clear",
        team1_score: 0,
        team2_score: 1,
        team1: ['Courtois', 'Puyol', 'Van Persie', 'Pedri', 'Neymar', 'Kane'],
        team2: ['Van Der Sar', 'Hummels', 'Berbatov', 'Modric', 'Vinicius', 'Suarez'],
        yellows: ['Suarez'],
        reds: [],
        goals: [
          { p: "Vinicius", a: "Modric", special: "", side: "team2" },
        ],
        clean_sheets: ['Van Der Sar', 'Hummels', 'Berbatov', 'Modric', 'Vinicius', 'Suarez'],
        penalties_missed: [],
        motm: "Modric",
        events: ['Berbatov has now played 5/5 games']
      },
      {
        id: 6,
        month: "january",
        match_number: 6,
        date: "15/01/2026",
        time: "17:05",
        referee: "Headband",
        condition: "Clear",
        team1_score: 0,
        team2_score: 3,
        team1: ['Russian Keeper', 'Hummels', 'Joaquin', 'Eriksen', 'Gakpo', 'Lewandowski'],
        team2: ['2-Face', 'Puyol', 'Assuncao', 'Pedri', 'Bale', 'Martinez'],
        yellows: [],
        reds: [],
        goals: [
          { p: "Martinez", a: "Pedrei", special: "", side: "team2" },
          { p: "Bale", a: "Martinez", special: "", side: "team2" },
          { p: "Pedri", a: "Bale", special: "", side: "team2" },
        ],
        clean_sheets: ['2-Face', 'Puyol', 'Assuncao', 'Pedri', 'Bale', 'Martinez'],
        penalties_missed: [],
        motm: "",
        events: ['Bale cut in on Joaquin and bent it top corner finesse', 'Pedri diving header, got it just in front of Martinez']
      },



      /*
    {
        id: 1,
        month: "january",
        match_number: 1,
        date: "01/01/2026",
        time: "",
        referee: "",
        condition: "Clear",
        team1_score: 0,
        team2_score: 0,
        team1: [""],
        team2: [""],
        yellows: [""],
        reds: [],
        goals: [
            { p: "Pele", a: "Kroos", special: "Slinger", side: "team1" },

          ],
        penalties_missed: [],
        motm: "",
      },
  */
]